name: Go Build and Test

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nmap arp-scan zenity wireshark

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m
        skip-cache: true      # Skip cache to avoid file exists errors
        skip-pkg-cache: true  # Skip package cache
        skip-build-cache: true # Skip build cache

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'

    - name: Build Release Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o netutil-linux-amd64

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          netutil-linux-amd64
        generate_release_notes: true
